default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["TODO_DATABASE_USER"] %>
  password: <%= ENV["TODO_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5433  # Usa el puerto 5433 en lugar del 5432
  pool: 5

development:
  <<: *default
  database: todo-rails-dev

test:
  <<: *default
  database: todo-rails-dev

production:
  <<: *default
  database: myapp_production
  username: <%= ENV["TODO_DATABASE_USER"] %>
  password: <%= ENV["TODO_DATABASE_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
